In [ ]:
n = int(input())
X = []
for i in range(n):
    X.append([float(x) for x in input().split()])
y = [int(x) for x in input().split()]
datapoint = [float(x) for x in input().split()]

6
1 3
3 5
5 7
3 1
5 3
7 5
1 1 1 0 0 0
2 4


In [ ]:
print(X)

[[1.0, 3.0], [3.0, 5.0], [5.0, 7.0], [3.0, 1.0], [5.0, 3.0], [7.0, 5.0]]


In [ ]:
print(y)

[1, 1, 1, 0, 0, 0]


In [ ]:
print(datapoint)

[2.0, 4.0]


In [ ]:
import numpy as np

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [ ]:
x = np.array(X).reshape(-1,2)
print(x)

[[1. 3.]
 [3. 5.]
 [5. 7.]
 [3. 1.]
 [5. 3.]
 [7. 5.]]


In [ ]:
y = np.array(y).reshape(-1,1)
print(y)

[[1]
 [1]
 [1]
 [0]
 [0]
 [0]]


In [ ]:
model.fit(x,y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [ ]:
datapoint = np.array(datapoint).reshape(-1,2)
print(datapoint)

[[2. 4.]]


In [ ]:
predict = model.predict(datapoint)
print(predict[0])

1


In [ ]:
model = LogisticRegression()
x = np.array(X).reshape(-1,2)
y = np.array(y)
model.fit(x,y)
datapoint = np.array(datapoint).reshape(-1,2)
predict = model.predict(datapoint)
print(predict[0])

1


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(x)
print(df)

In [ ]:
x = df[[0,1]].values
print(x)

[[1. 3.]
 [3. 5.]
 [5. 7.]
 [3. 1.]
 [5. 3.]
 [7. 5.]]


In [ ]:
model = LogisticRegression()
y = np.array(y)
model.fit(x,y)
datapoint = np.array(datapoint).reshape(-1,2)
predict = model.predict(datapoint)
print(predict[0])

1


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
